# Generated by Django 5.2 on 2025-04-04 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Lager.category'),
            preserve_default=False,
        ),
    ]
