# Generated by Django 5.2 on 2025-04-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lager', '0002_producttype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
