# Generated by Django 5.2 on 2025-04-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lager', '0004_remove_orderitem_product_orderitem_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='current_stock_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
