# Generated by Django 5.2 on 2025-04-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lager', '0005_producttype_current_stock_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Liefertermin'),
        ),
    ]
