# Generated by Django 5.2 on 2025-04-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lager', '0006_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Liefertermin'),
        ),
    ]
