# Generated by Django 5.2 on 2025-04-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lager', '0007_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Erledigt'),
        ),
    ]
